var default_spec = {
    spec: {
    COLOR_TEMPERATURE: "6,500K",
    PIXEL_PITCH: "1.26 mm",
    DIMENSIONS: "806.4x453.6x76.7mm",
    SERIES_NAME: "IF Series",
    PRODUCT_NAME: "IF012J",
    REFRESH_RATE: "3,840 Hz",
    LED_LIFETIME: "100,000 hours",
    POWER_CONSUMPTION_TYPICAL1: "237",
    SEQ: 1279,
    POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/㎡)",
    POWER_CONSUMPTION_MAX1: "711",
    BRIGHTNESS: "1,200 nit / 600 nit",
    POWER_CONSUMPTION_MAX2: "260",
    POWER_CONSUMPTION_MAX: "711 (W/㎡) / 260 (W/Cabinet)",
    POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
    CATEGORY: "Indoor",
    POWER_CONSUMPTION_TYPICAL: "237 (W/㎡) / 87 (W/Cabinet)",
    POWER_CONSUMPTION_TYPICAL2: "87",
    WEIGHT: "11.8kg",
    POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
    URL: "/led-signage/detail/1279/IF012J",
    CABINET_MODULE_CONFIGURATION: "640x360 pixels",
    POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
    CONTRAST_RATIO: "8,000:1 / 4,000:1"
    }
};
var outdoor_spec = {
    1391: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "16.5mm (.65″) centers",
        DIMENSIONS: "264x264 mm",
        SERIES_NAME: "XPB Series",
        PRODUCT_NAME: "XPB160",
        REFRESH_RATE: "24,960hz",
        LED_LIFETIME: "",
        POWER_CONSUMPTION_TYPICAL1: "183",
        SEQ: 1391,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/㎡)",
        POWER_CONSUMPTION_MAX1: "348",
        BRIGHTNESS: "9,000 nit",
        POWER_CONSUMPTION_MAX2: "32.7",
        POWER_CONSUMPTION_MAX: "348 (W/㎡) / 32.7 (W/ft2)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "183 (W/㎡) / 17.2 (W/ft2)",
        POWER_CONSUMPTION_TYPICAL2: "17.2",
        WEIGHT: "71.5kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft2)",
        URL: "/led-signage/detail/1391/XPB160",
        CABINET_MODULE_CONFIGURATION: "16x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft2)",
        CONTRAST_RATIO: "11,000:1"
        }
    },
    1390: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "10.32mm (.40625″) centers",
        DIMENSIONS: "330x165 mm",
        SERIES_NAME: "XPB Series",
        PRODUCT_NAME: "XPB100",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "",
        POWER_CONSUMPTION_TYPICAL1: "184",
        SEQ: 1390,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/㎡)",
        POWER_CONSUMPTION_MAX1: "737",
        BRIGHTNESS: "7,500 nit",
        POWER_CONSUMPTION_MAX2: "68.5",
        POWER_CONSUMPTION_MAX: "737 (W/㎡) / 68.5 (W/ft2)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "184 (W/㎡) / 17.1 (W/ft2)",
        POWER_CONSUMPTION_TYPICAL2: "17.1",
        WEIGHT: "111.8kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft2)",
        URL: "/led-signage/detail/1390/XPB100",
        CABINET_MODULE_CONFIGURATION: "32x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft2)",
        CONTRAST_RATIO: "10,000:1"
        }
    },
    1389: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "8.255mm (.325″) centers",
        DIMENSIONS: "264x297 mm",
        SERIES_NAME: "XPB Series",
        PRODUCT_NAME: "XPB080",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "",
        POWER_CONSUMPTION_TYPICAL1: "184",
        SEQ: 1389,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/㎡)",
        POWER_CONSUMPTION_MAX1: "735",
        BRIGHTNESS: "7,500 nit",
        POWER_CONSUMPTION_MAX2: "68.3",
        POWER_CONSUMPTION_MAX: "735 (W/㎡) / 68.3 (W/ft2)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "184 (W/㎡) / 17.1 (W/ft2)",
        POWER_CONSUMPTION_TYPICAL2: "17.1",
        WEIGHT: "91.9kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft2)",
        URL: "/led-signage/detail/1389/XPB080",
        CABINET_MODULE_CONFIGURATION: "32x36 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft2)",
        CONTRAST_RATIO: "10,000:1"
        }
    },
    1388: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "10.32mm",
        DIMENSIONS: "330x165 mm",
        SERIES_NAME: "XPE Series",
        PRODUCT_NAME: "XPE100",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours (* in normal usage)",
        POWER_CONSUMPTION_TYPICAL1: "184",
        SEQ: 1388,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m˛)",
        POWER_CONSUMPTION_MAX1: "737",
        BRIGHTNESS: "160° (+/- 80°)",
        POWER_CONSUMPTION_MAX2: "68.5",
        POWER_CONSUMPTION_MAX: "737 (W/m˛) / 68.5 (W/ft˛)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m˛)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "184 (W/m˛) / 17.1 (W/ft˛)",
        POWER_CONSUMPTION_TYPICAL2: "17.1",
        WEIGHT: "0.69kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft˛)",
        URL: "/led-signage/detail/1388/XPE100",
        CABINET_MODULE_CONFIGURATION: "32x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft˛)",
        CONTRAST_RATIO: ""
        }
    },
    1387: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "8.255mm",
        DIMENSIONS: "264x297 mm",
        SERIES_NAME: "XPE Series",
        PRODUCT_NAME: "XPE080",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours (* in normal usage)",
        POWER_CONSUMPTION_TYPICAL1: "184",
        SEQ: 1387,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "735",
        BRIGHTNESS: "7,500 nit",
        POWER_CONSUMPTION_MAX2: "68.3",
        POWER_CONSUMPTION_MAX: "735 (W/m²) / 68.3 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "184 (W/m²) / 17.1 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "17.1",
        WEIGHT: "1kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1387/XPE080",
        CABINET_MODULE_CONFIGURATION: "32x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: ""
        }
    },
    1386: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "6.35mm",
        DIMENSIONS: "203x203 mm",
        SERIES_NAME: "XPE Series",
        PRODUCT_NAME: "XPE060",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours (* in normal usage)",
        POWER_CONSUMPTION_TYPICAL1: "207",
        SEQ: 1386,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "827",
        BRIGHTNESS: "7,500 nit",
        POWER_CONSUMPTION_MAX2: "76.8",
        POWER_CONSUMPTION_MAX: "827 (W/m²) / 76.8 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "207 (W/m²) / 19.2 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "19.2",
        WEIGHT: "0.54kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1386/XPE060",
        CABINET_MODULE_CONFIGURATION: "32x32 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: ""
        }
    },
    1129: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "16.0 mm",
        DIMENSIONS: "960x960x154 (per cabinet)",
        SERIES_NAME: "XAF Series",
        PRODUCT_NAME: "XA160F",
        REFRESH_RATE: "≧4000 Hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "220",
        SEQ: 1129,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "650",
        BRIGHTNESS: "7,700 nit",
        POWER_CONSUMPTION_MAX2: "60.4",
        POWER_CONSUMPTION_MAX: "650 (W/m²) / 60.4 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "220 (W/m²) / 20.4 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "20.4",
        WEIGHT: "55kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1129/XA160F",
        CABINET_MODULE_CONFIGURATION: "60 x 60 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "3,000:1"
        }
    },
    1128: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "10.0 mm",
        DIMENSIONS: "960x960x142 (per cabinet)",
        SERIES_NAME: "XAF Series",
        PRODUCT_NAME: "XA100F",
        REFRESH_RATE: "≧2000 Hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "320",
        SEQ: 1128,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "900",
        BRIGHTNESS: "6,750 nit",
        POWER_CONSUMPTION_MAX2: "83.6",
        POWER_CONSUMPTION_MAX: "900 (W/m²) / 83.6 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "320 (W/m²) / 29.7 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "29.7",
        WEIGHT: "52kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1128/XA100F",
        CABINET_MODULE_CONFIGURATION: "96 x 96 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "3,000:1"
        }
    },
    1127: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "8.0 mm",
        DIMENSIONS: "1152x864x142 (per cabinet)",
        SERIES_NAME: "XAF Series",
        PRODUCT_NAME: "XA080F",
        REFRESH_RATE: "≧2000 Hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "320",
        SEQ: 1127,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "900",
        BRIGHTNESS: "6,300 nit",
        POWER_CONSUMPTION_MAX2: "83.6",
        POWER_CONSUMPTION_MAX: "900 (W/m²) / 83.6 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "320 (W/m²) / 29.7 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "29.7",
        WEIGHT: "56kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1127/XA080F",
        CABINET_MODULE_CONFIGURATION: "144 x 108 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "3,000:1"
        }
    },
    1126: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "6.0 mm",
        DIMENSIONS: "1152x864x142 (per cabinet) ",
        SERIES_NAME: "XAF Series",
        PRODUCT_NAME: "XA060F",
        REFRESH_RATE: "≧2000 Hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "350",
        SEQ: 1126,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "1000",
        BRIGHTNESS: "6,300 nit",
        POWER_CONSUMPTION_MAX2: "92.9",
        POWER_CONSUMPTION_MAX: "1000 (W/m²) / 92.9 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "350 (W/m²) / 32.5 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "32.5",
        WEIGHT: "56kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1126/XA060F",
        CABINET_MODULE_CONFIGURATION: "192x144 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "3,000:1"
        }
    },
    1122: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "10.0 mm",
        DIMENSIONS: "1280x960x168 (per cabinet)",
        SERIES_NAME: "XRF Series",
        PRODUCT_NAME: "XR100F",
        REFRESH_RATE: "≧3000",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "240",
        SEQ: 1122,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "750",
        BRIGHTNESS: "6,750 nit",
        POWER_CONSUMPTION_MAX2: "69.7",
        POWER_CONSUMPTION_MAX: "750 (W/m²) / 69.7 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "240 (W/m²) / 22.3 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "22.3",
        WEIGHT: "52kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1122/XR100F",
        CABINET_MODULE_CONFIGURATION: "128 x 96 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "3,000:1"
        }
    },
    947: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "8.255mm (.325″) centers",
        DIMENSIONS: "264x297 mm (per module)",
        SERIES_NAME: "XPS Series",
        PRODUCT_NAME: "XPS080",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "176",
        SEQ: 947,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "704",
        BRIGHTNESS: "9,000 nit",
        POWER_CONSUMPTION_MAX2: "65",
        POWER_CONSUMPTION_MAX: "704 (W/m²) / 65 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "176 (W/m²) / 16.4 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "16.4",
        WEIGHT: "1kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/947/XPS080",
        CABINET_MODULE_CONFIGURATION: "32 x 36 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "11,000:1"
        }
    },
    821: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "20.6mm (.8125″) centers",
        DIMENSIONS: "330x165 mm (per module)",
        SERIES_NAME: "XPS Series",
        PRODUCT_NAME: "XPS200",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "169",
        SEQ: 821,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "329",
        BRIGHTNESS: "9,000 nit",
        POWER_CONSUMPTION_MAX2: "30.5",
        POWER_CONSUMPTION_MAX: "329 (W/m²) / 30.5 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "169 (W/m²) / 15.7 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "15.7",
        WEIGHT: "0.95kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/821/XPS200",
        CABINET_MODULE_CONFIGURATION: "16 x 8 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "12,000:1"
        }
    },
    820: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "25.4mm (1.0″) centers",
        DIMENSIONS: "406x203 mm (per module)",
        SERIES_NAME: "XPS Series",
        PRODUCT_NAME: "XPS250",
        REFRESH_RATE: "24,960hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "169",
        SEQ: 820,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "318",
        BRIGHTNESS: "7,500 nit",
        POWER_CONSUMPTION_MAX2: "29.5",
        POWER_CONSUMPTION_MAX: "318 (W/m²) / 29.5 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "169 (W/m²) / 15.7 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "15.7",
        WEIGHT: "1.38kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/820/XPS250",
        CABINET_MODULE_CONFIGURATION: "16x8 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "12,000:1"
        }
    },
    819: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "16.5mm (.65″) centers",
        DIMENSIONS: "264x264 mm (per module)",
        SERIES_NAME: "XPS Series",
        PRODUCT_NAME: "XPS160",
        REFRESH_RATE: "24,960hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "183",
        SEQ: 819,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "348",
        BRIGHTNESS: "9,000 nit",
        POWER_CONSUMPTION_MAX2: "32.7",
        POWER_CONSUMPTION_MAX: "348 (W/m²) / 32.7 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "183 (W/m²) / 17.2 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "17.2",
        WEIGHT: "1.16kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/819/XPS160",
        CABINET_MODULE_CONFIGURATION: "16x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "11,000:1"
        }
    },
    818: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "16.5mm (.65″) centers",
        DIMENSIONS: "264x264 mm (per module)",
        SERIES_NAME: "XPS Series",
        PRODUCT_NAME: "XPS165",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "156",
        SEQ: 818,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "624",
        BRIGHTNESS: "7,500 nit",
        POWER_CONSUMPTION_MAX2: "58.5",
        POWER_CONSUMPTION_MAX: "624 (W/m²) / 58.5 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "156 (W/m²) / 14.6 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "14.6",
        WEIGHT: "0.95kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/818/XPS165",
        CABINET_MODULE_CONFIGURATION: "16x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "21,000:1"
        }
    },
    817: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "12.7mm (.5″) centers",
        DIMENSIONS: "203x203 mm (per module)",
        SERIES_NAME: "XPS Series",
        PRODUCT_NAME: "XPS120",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "202",
        SEQ: 817,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "806",
        BRIGHTNESS: "9,000 nit",
        POWER_CONSUMPTION_MAX2: "74.9",
        POWER_CONSUMPTION_MAX: "806 (W/m²) / 74.9 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "202 (W/m²) / 18.7 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "18.7",
        WEIGHT: "0.61kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/817/XPS120",
        CABINET_MODULE_CONFIGURATION: "16 x 16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "18,000:1"
        }
    },
    815: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "10.32mm (.40625″) centers",
        DIMENSIONS: "330x165 mm (per module)",
        SERIES_NAME: "XPS Series",
        PRODUCT_NAME: "XPS100",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "179",
        SEQ: 815,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "714",
        BRIGHTNESS: "9,000 nit",
        POWER_CONSUMPTION_MAX2: "66",
        POWER_CONSUMPTION_MAX: "714 (W/m²) / 66 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "179 (W/m²) / 16.6 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "16.6",
        WEIGHT: "0.69kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/815/XPS100",
        CABINET_MODULE_CONFIGURATION: "32x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "13,000:1"
        }
    },
    814: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "6.35mm (.25″) centers",
        DIMENSIONS: "203x203 mm (per module)",
        SERIES_NAME: "XPS Series",
        PRODUCT_NAME: "XPS060",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "248",
        SEQ: 814,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "992",
        BRIGHTNESS: "9,000 nit",
        POWER_CONSUMPTION_MAX2: "92.5",
        POWER_CONSUMPTION_MAX: "992 (W/m²) / 92.5 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Outdoor",
        POWER_CONSUMPTION_TYPICAL: "248 (W/m²) / 23.1 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "23.1",
        WEIGHT: "0.54kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/814/XPS060",
        CABINET_MODULE_CONFIGURATION: "32 x 32 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "11,000:1"
        }
    }
};
var indoor_spec = {
    1340: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "2.5 ?",
        DIMENSIONS: "480x540x65mm",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF025H-E",
        REFRESH_RATE: "1,920Hz, 3,840 Hz Selectable",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "206",
        SEQ: 1340,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/㎡)",
        POWER_CONSUMPTION_MAX1: "620",
        BRIGHTNESS: "2,000 nit / 1,000 nit",
        POWER_CONSUMPTION_MAX2: "160",
        POWER_CONSUMPTION_MAX: "620 (W/㎡) / 160 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "206 (W/㎡) / 54 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "54",
        WEIGHT: "5.8kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1340/IF025H-E",
        CABINET_MODULE_CONFIGURATION: "192x216 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "10,000:1 / 5,000:1"
        }
    },
    1339: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "1.5 mm",
        DIMENSIONS: "480x540x65mm",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF015H-E",
        REFRESH_RATE: "1,920Hz, 3,840 Hz Selectable",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "258",
        SEQ: 1339,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/㎡)",
        POWER_CONSUMPTION_MAX1: "770",
        BRIGHTNESS: "1,200 nit / 600 nit",
        POWER_CONSUMPTION_MAX2: "200",
        POWER_CONSUMPTION_MAX: "770 (W/㎡) / 200 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "258 (W/㎡) / 68 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "68",
        WEIGHT: "5.8kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1339/IF015H-E",
        CABINET_MODULE_CONFIGURATION: "320x360 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "10,000:1 / 5,000:1"
        }
    },
    1279: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "1.26 mm",
        DIMENSIONS: "806.4x453.6x76.7mm",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF012J",
        REFRESH_RATE: "3,840 Hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "237",
        SEQ: 1279,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/㎡)",
        POWER_CONSUMPTION_MAX1: "711",
        BRIGHTNESS: "1,200 nit / 600 nit",
        POWER_CONSUMPTION_MAX2: "260",
        POWER_CONSUMPTION_MAX: "711 (W/㎡) / 260 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "237 (W/㎡) / 87 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "87",
        WEIGHT: "11.8kg",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1279/IF012J",
        CABINET_MODULE_CONFIGURATION: "640x360 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "8,000:1 / 4,000:1"
        }
    },
    1251: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "6.0 mm",
        DIMENSIONS: "480x720x65mm (per cabinet)",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF060H-D",
        REFRESH_RATE: "1,920Hz, 3,840 Hz Selectable",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "193",
        SEQ: 1251,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "580",
        BRIGHTNESS: "1,800 nit / 1,200 nit",
        POWER_CONSUMPTION_MAX2: "200",
        POWER_CONSUMPTION_MAX: "580 (W/m²) / 200 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "193 (W/m²) / 67 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "67",
        WEIGHT: "7.4kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1251/IF060H-D",
        CABINET_MODULE_CONFIGURATION: "80 x 120 pixels (per cabinet)",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "7,500:1 / 5,000:1"
        }
    },
    1250: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "4.0 mm",
        DIMENSIONS: "480x720x65 mm (per cabinet)",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF040H-D",
        REFRESH_RATE: "1,920Hz, 3,840 Hz Selectable",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "193",
        SEQ: 1250,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "580",
        BRIGHTNESS: "1,700 nit / 1,200 nit",
        POWER_CONSUMPTION_MAX2: "200",
        POWER_CONSUMPTION_MAX: "580 (W/m²) / 200 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "193 (W/m²) / 67 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "67",
        WEIGHT: "7.4kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1250/IF040H-D",
        CABINET_MODULE_CONFIGURATION: "120 x 180 pixels (per cabinet)",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "7,000:1 / 5,000:1"
        }
    },
    1249: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "2.5 mm",
        DIMENSIONS: "480x720x65 mm (per cabinet)",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF025H-D",
        REFRESH_RATE: "1,920Hz, 3,840 Hz Selectable",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "193",
        SEQ: 1249,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "580",
        BRIGHTNESS: "2,400 nit / 1,200 nit",
        POWER_CONSUMPTION_MAX2: "200",
        POWER_CONSUMPTION_MAX: "580 (W/m²) / 200 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "193 (W/m²) / 67 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "67",
        WEIGHT: "7.4kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1249/IF025H-D",
        CABINET_MODULE_CONFIGURATION: "192 x 288 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "10,000:1 / 5,000:1"
        }
    },
    1140: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "10.32mm (.400″) centers",
        DIMENSIONS: "330x165 mm (per module)",
        SERIES_NAME: "IPE Series",
        PRODUCT_NAME: "IPE100",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours (* in normal usage)",
        SEQ: 1140,
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX: "TBD",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "TBD",
        WEIGHT: "0.27kg (per module)",
        URL: "/led-signage/detail/1140/IPE100",
        CABINET_MODULE_CONFIGURATION: "32x16 pixels",
        CONTRAST_RATIO: "TBD"
        }
    },
    1139: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "6.35mm (.25″) centers",
        DIMENSIONS: "203x229 mm (per module)",
        SERIES_NAME: "IPE Series",
        PRODUCT_NAME: "IPE060",
        REFRESH_RATE: "10,500hz",
        LED_LIFETIME: "100,000 hours (* in normal usage)",
        POWER_CONSUMPTION_TYPICAL1: "161",
        SEQ: 1139,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "644",
        BRIGHTNESS: "1,400 nit",
        POWER_CONSUMPTION_MAX2: "59.8",
        POWER_CONSUMPTION_MAX: "644 (W/m²) / 59.8 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "161 (W/m²) / 14.9 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "14.9",
        WEIGHT: "0.32kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1139/IPE060",
        CABINET_MODULE_CONFIGURATION: "32x36 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "8,000:1"
        }
    },
    1137: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "4.1275mm (.1625″) centers",
        DIMENSIONS: "264x297 mm (per module)",
        SERIES_NAME: "IPE Series",
        PRODUCT_NAME: "IPE040",
        REFRESH_RATE: "10,500hz",
        LED_LIFETIME: "100,000 hours (* in normal usage)",
        POWER_CONSUMPTION_TYPICAL1: "165",
        SEQ: 1137,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "660.4",
        BRIGHTNESS: "1,800 nit",
        POWER_CONSUMPTION_MAX2: "61.3",
        POWER_CONSUMPTION_MAX: "660.4 (W/m²) / 61.3 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "165 (W/m²) / 15.3 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "15.3",
        WEIGHT: "0.52kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1137/IPE040",
        CABINET_MODULE_CONFIGURATION: "64x72 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "13,500:1"
        }
    },
    1136: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "3.175mm (.125″) centers",
        DIMENSIONS: "203x229 mm (per module)",
        SERIES_NAME: "IPE Series",
        PRODUCT_NAME: "IPE030",
        REFRESH_RATE: "10,500hz",
        LED_LIFETIME: "100,000 hours (* in normal usage)",
        POWER_CONSUMPTION_TYPICAL1: "223.2",
        SEQ: 1136,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "892.8",
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX2: "82.9",
        POWER_CONSUMPTION_MAX: "892.8 (W/m²) / 82.9 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "223.2 (W/m²) / 20.7 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "20.7",
        WEIGHT: "0.34kg (need to verify)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/1136/IPE030",
        CABINET_MODULE_CONFIGURATION: "64x72 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "6,000:1"
        }
    },
    1094: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "2.5 mm ",
        DIMENSIONS: "480x540x65 mm (per cabinet)",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF025H",
        REFRESH_RATE: "1,920Hz, 3,840 Hz Selectable",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "206",
        SEQ: 1094,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "620",
        BRIGHTNESS: "2,400 nit / 1,200 nit",
        POWER_CONSUMPTION_MAX2: "160",
        POWER_CONSUMPTION_MAX: "620 (W/m²) / 160 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "206 (W/m²) / 54 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "54",
        WEIGHT: "5.8kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1094/IF025H",
        CABINET_MODULE_CONFIGURATION: "192 x 216 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "10,000:1 / 5,000:1"
        }
    },
    1093: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "2.0 mm",
        DIMENSIONS: "480x540x65 mm (per cabinet)",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF020H",
        REFRESH_RATE: "1,920Hz, 3,840 Hz Selectable",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "232",
        SEQ: 1093,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "695",
        BRIGHTNESS: "2,400 nit / 1,200 nit",
        POWER_CONSUMPTION_MAX2: "180",
        POWER_CONSUMPTION_MAX: "695 (W/㎡) / 180 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "232 (W/m²) / 60 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "60",
        WEIGHT: "5.8kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1093/IF020H",
        CABINET_MODULE_CONFIGURATION: "240 x 270 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "10,000:1 / 5,000:1"
        }
    },
    1092: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "1.5 mm ",
        DIMENSIONS: "480x540x65 mm (per cabinet)",
        SERIES_NAME: "IF Series",
        PRODUCT_NAME: "IF015H",
        REFRESH_RATE: "1,920Hz, 3,840 Hz Selectable",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "258",
        SEQ: 1092,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "770",
        BRIGHTNESS: "1,600 nit / 800 nit",
        POWER_CONSUMPTION_MAX2: "200",
        POWER_CONSUMPTION_MAX: "770 (W/m²) / 200 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "258 (W/m²) / 68 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "68",
        WEIGHT: "5.8kg (per cabinet)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1092/IF015H",
        CABINET_MODULE_CONFIGURATION: "320 x 360 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "10,000:1 / 5,000:1"
        }
    },
    813: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "16.51mm (.65″) centers",
        DIMENSIONS: "264x264 mm (per module)",
        SERIES_NAME: "IPS Series",
        PRODUCT_NAME: "IPS160",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "142",
        SEQ: 813,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "474",
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX2: "44.1",
        POWER_CONSUMPTION_MAX: "474 (W/m²) / 44.1 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "142 (W/m²) / 13.2 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "13.2",
        WEIGHT: "0.44kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/813/IPS160",
        CABINET_MODULE_CONFIGURATION: "16x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "13,000:1"
        }
    } ,
    812: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "12.7mm (.5″) centers",
        DIMENSIONS: "203x203 mm (per module)",
        SERIES_NAME: "IPS Series",
        PRODUCT_NAME: "IPS120",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "143",
        SEQ: 812,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "490",
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX2: "45.5",
        POWER_CONSUMPTION_MAX: "490 (W/m²) / 45.5 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "143 (W/m²) / 13.2 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "13.2",
        WEIGHT: "0.27kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/812/IPS120",
        CABINET_MODULE_CONFIGURATION: "16x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "19,000:1"
        }
    },
    811: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "10.32mm (.400″) centers",
        DIMENSIONS: "330x165 mm (per module)",
        SERIES_NAME: "IPS Series",
        PRODUCT_NAME: "IPS100",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "123.5",
        SEQ: 811,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "494",
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX2: "45.9",
        POWER_CONSUMPTION_MAX: "494 (W/m²) / 45.9 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "123.5 (W/m²) / 11.5 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "11.5",
        WEIGHT: "0.27kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/811/IPS100",
        CABINET_MODULE_CONFIGURATION: "32x16 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "8,000:1"
        }
    },
    810: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "8.255mm (.325″) centers",
        DIMENSIONS: "264x297 mm (per module)",
        SERIES_NAME: "IPS Series",
        PRODUCT_NAME: "IPS080",
        REFRESH_RATE: "49,920hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "190",
        SEQ: 810,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "543",
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX2: "50.4",
        POWER_CONSUMPTION_MAX: "543 (W/m²) / 50.4 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "190 (W/m²) / 21.3 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "21.3",
        WEIGHT: "0.50kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/810/IPS080",
        CABINET_MODULE_CONFIGURATION: "32x36 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "13,000:1"
        }
    },
    809: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "6.35mm (.25″) centers",
        DIMENSIONS: "203x229 mm (per module)",
        SERIES_NAME: "IPS Series",
        PRODUCT_NAME: "IPS060",
        REFRESH_RATE: "10,500hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "142",
        SEQ: 809,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "570",
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX2: "53",
        POWER_CONSUMPTION_MAX: "570 (W/m²) / 53 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "142 (W/m²) / 13.2 (W/ft²) ",
        POWER_CONSUMPTION_TYPICAL2: "13.2",
        WEIGHT: "0.32kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/809/IPS060",
        CABINET_MODULE_CONFIGURATION: "32x36 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "11500:1"
        }
    },
    808: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "4.1275mm (.1625″) centers",
        DIMENSIONS: "264x297 mm (per module)",
        SERIES_NAME: "IPS Series",
        PRODUCT_NAME: "IPS040",
        REFRESH_RATE: "10,500hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "132",
        SEQ: 808,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "528.3",
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX2: "49.1",
        POWER_CONSUMPTION_MAX: "528.3 (W/m²) / 49.1 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "132 (W/m²) / 12.3 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "12.3",
        WEIGHT: "0.52kg (per module)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/808/IPS040",
        CABINET_MODULE_CONFIGURATION: "64x72 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "15000:1"
        }
    },
    807: {
        spec: {
        COLOR_TEMPERATURE: "6,500K",
        PIXEL_PITCH: "3.175mm (.125″) centers",
        DIMENSIONS: "203x229 mm (per module)",
        SERIES_NAME: "IPS Series",
        PRODUCT_NAME: "IPS030",
        REFRESH_RATE: "10,500hz",
        LED_LIFETIME: "100,000 hours",
        POWER_CONSUMPTION_TYPICAL1: "223.2",
        SEQ: 807,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/m²)",
        POWER_CONSUMPTION_MAX1: "892.8",
        BRIGHTNESS: "2,000 nit",
        POWER_CONSUMPTION_MAX2: "82.9",
        POWER_CONSUMPTION_MAX: "892.8 (W/m²) / 82.9 (W/ft²)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/m²)",
        CATEGORY: "Indoor",
        POWER_CONSUMPTION_TYPICAL: "223.2 (W/m²) / 20.7 (W/ft²)",
        POWER_CONSUMPTION_TYPICAL2: "20.7",
        WEIGHT: "0.34kg (need to verify)",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/ft²)",
        URL: "/led-signage/detail/807/IPS030",
        CABINET_MODULE_CONFIGURATION: "64x72 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/ft²)",
        CONTRAST_RATIO: "6,000:1"
        }
    }
};
var thewall_spec = {
    1346: {
        spec: {
        COLOR_TEMPERATURE: "",
        PIXEL_PITCH: " 0.8 mm",
        DIMENSIONS: "806.4x453.6x72.5 mm",
        SERIES_NAME: "The Wall Series",
        PRODUCT_NAME: "IW008J",
        REFRESH_RATE: "3,840 Hz",
        LED_LIFETIME: "",
        POWER_CONSUMPTION_TYPICAL1: "210.7",
        SEQ: 1346,
        POWER_CONSUMPTION_TYPICAL1_UNIT: "(W/㎡)",
        POWER_CONSUMPTION_MAX1: "628.9",
        BRIGHTNESS: "1,600 nit / 500 nit",
        POWER_CONSUMPTION_MAX2: "230",
        POWER_CONSUMPTION_MAX: "628.9 (W/㎡) / 230 (W/Cabinet)",
        POWER_CONSUMPTION_MAX1_UNIT: "(W/㎡)",
        CATEGORY: "The Wall",
        POWER_CONSUMPTION_TYPICAL: "210.7 (W/㎡) / 77.1 (W/Cabinet)",
        POWER_CONSUMPTION_TYPICAL2: "77.1",
        WEIGHT: "11.8 kg / 26 lbs",
        POWER_CONSUMPTION_TYPICAL2_UNIT: "(W/Cabinet)",
        URL: "/led-signage/detail/1346/IW008J",
        CABINET_MODULE_CONFIGURATION: "960 x 540 pixels",
        POWER_CONSUMPTION_MAX2_UNIT: "(W/Cabinet)",
        CONTRAST_RATIO: "20,000:1"
        }
    }
}